source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView


app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api.views import QuoteViewSet

app_name = 'api'

router = DefaultRouter()
router.register('quote', QuoteViewSet, basename='quote')

urlpatterns = [
    path('', include(router.urls))
]

source/source/urls.py
from django.contrib import admin
from django.urls import path, include
from source import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import IndexView

app_name = 'webapp'

urlpatterns = [
path('', IndexView.as_view(), name='index'),
]

source/webapp/models.py
from django.db import models
from django.contrib.sessions.models import Session

STATUS_NEW = 'new'
STATUS_MODERATED = 'moderated'
STATUS_CHOICES = (
    (STATUS_NEW, 'New'),
    (STATUS_MODERATED, "Moderated")
)

DEFAULT_STATUS = STATUS_NEW


class Quote(models.Model):
    text = models.TextField(max_length=200, verbose_name='Text')
    author = models.CharField(max_length=100, verbose_name="Author")
    email = models.EmailField(verbose_name='E-mail')
    rating = models.IntegerField(default=0, verbose_name='Rating')
    status = models.CharField(max_length=15, verbose_name='Status', choices=STATUS_CHOICES, default=DEFAULT_STATUS)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')

    @classmethod
    def get_moderated(cls):
        return cls.objects.filter(status=STATUS_MODERATED)

    def __str__(self):
        return f'{self.text[:20]}'

    class Meta:
        verbose_name = 'Quote'
        verbose_name_plural = 'Quotes'
        ordering = ('-created_at',)


class Vote(models.Model):
    session_key = models.CharField(max_length=40, verbose_name='Session key')
    quote = models.ForeignKey('webapp.Quote', related_name='votes', on_delete=models.CASCADE, verbose_name='Quote')
    rating = models.IntegerField(choices=((1, 'up',), (-1, 'down')), verbose_name='Rating')

    def __str__(self):
        return f'{self.quote}: {self.rating}'

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'
        ordering = ('quote', 'rating')

source/webapp/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import View


class IndexView(View):
    @method_decorator(ensure_csrf_cookie)
    def get(self, request, *args, **kwargs):
        return render(request, 'index.html')

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Quotes{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
                <li><a href="{% url 'webapp:index' %}">Home</a></li>
                {% block menu %}{% endblock %}
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">
                        Привет, {{ request.user.get_full_name|default:request.user.username }}
                    </a></li>
                {% endif %}
                {% block auth_menu %}
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>
                        <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sign Up</a></li>
                    {% endif %}
                {% endblock %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:password_reset_email' %}">Reset Password</a></li>
                {% endif %}
            </ul>

            {% block search %}
                {% if search_form %}
                    <div class="search-form">
                        <form action="{% url 'webapp:index' %}" method="GET">
                            {{ search_form.search }}
                            <input type="submit" value="Find">
                        </form>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </nav>
    <div class="container">
        {% include 'partial/messages.html' %}
        {% block content %}{% endblock %}
        {% block quote %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'api:quote-list' %}" method="post" id="quote_create_form">
        <p><input type="text" name="text" placeholder="Text"></p>
        <p><input type="text" name="author" placeholder="Author"></p>
        <p><input type="text" name="email" placeholder="Email"></p>
        <input type="submit" value="Add">
    </form>
{% endblock %}

{% block quote %}
    <p id="text"></p>
    <p id="created_at"></p>
    <p id="rating"></p>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/api_client.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/form_control.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/api.js' %}"></script>
{% endblock %}